### PR TITLE
V10 updates

### PR DESCRIPTION
**Pull request by drewg13**
These are pretty extensive, but I tried to limit the scope to just what was needed to get it working in V10, but some more opinionated edits might have slipped in there.  Apologies, if so.

There were also significant changes needed to the system manifest, so you're going to want to review the `version` and `download` fields to make sure they match with your release version filename.  I picked `4.00` somewhat arbitrarily.

The other major issue to be aware of is that maintaining V9 back-compatibility is very challenging, so I didn't even attempt it.  It's going to be a hard break unless someone wants to put in a ton of work.

### CODE REVIEW

**Comment by megastruktur** [comment]
@drewg13 thanks a lot for this PR. I'll review it today.
Regarding the backw compat - I think I'll just limit the "from" version to 10.x.

**Comment by megastruktur** [comment]
@drewg13 guh. Ok thanks let me see

**Comment by megastruktur** [comment]
@drewg13 I've change that, thanks.

**Comment by drewg13** [comment]
That fixed it, that should save some hassle later.  You may also want to add back some of the required V9 fields to `system.json`, as currently without them, V9 users get this:
image

You DO NOT have to make a new release or increment the version number, since checking for updates pulls the manifest fresh from github each time.

```json
"name": "blades-in-the-dark",
"minimumCoreVersion": 10,
```

Sorry, I forgot about that particular issue when putting together the PR.

**Comment by megastruktur** [comment]
@drewg13 Will fix that one ^
For me creating a new release it's a matter of 3 commands, that's why I'm doing that  :D
Could you please add me in Discord (megastruktur#5704)? I don't read emails often  :(

**Pull request merged**
