### PR TITLE
Improve sheets to be able to add the french version

### PR DESCRIPTION
**Pull request by DarkWizarD24**
The french version of the compendium uses bold and italic so I had to change the way it is edited and displayed.

French take more space, I couldn't fixes all the issues with a dedicated css sheet.

The french translation will include the compendium and leverage babele. So it will be distributed in a separated module.

### CODE REVIEW

**Comment by megastruktur** [comment]
Hey!
Why did you change the "textarea" to editor? I was using the textareas because it works "fasta" and doesn't wrap text into WYSIWYG clutter, but there may be a reason behind "editor" - that's why I'm asking.  :smile:

**Comment by DarkWizarD24** [comment]
I wanted to simplify the edition of compendium content with bold and italic content. It's a bit painful to do that in a simple textarea.

**Comment by cyberdwarf1664** [comment]
Without answer to my last mail, I made a babel translation of the compendium for your system :

https://github.com/cyberdwarf1664/Foundry-BiD-lang-fr

**Comment by DarkWizarD24** [comment]
I have done a similar thing : https://gitlab.com/DarkWizarD/blades-in-the-dark-fr
I used the traduction from 500 nuance de geek with their express autorisation. Do you have translated it yourself ?

You can send me an email to discuss the merging of our work : public@darkwizard.fr

**Pull request merged**
