### PR TITLE
Add quality of life interaction hinting to the character sheet, and a roll fix

### PR DESCRIPTION
**Pull request by OctarineSourcerer**
In a nutshell,
- Skill rolling is now done by clicking the skill itself - this is hinted at by it fading red when you mouse over it. Same with attributes. Makes it less cluttered with less dice around on the sheet, is intuitive, and gives feedback to the player.
- Teeth, clocks, dots and coins all fade/dim a little when you mouse over them, to hint that something can be done
- Same items also change the pointer
- Trauma teeth are exempt from this, as these are meant to be changed by adding/removing traumas
- Attribute text is capitalised

There is also a bugfix in here - when a skill or attribute is rolled, the dice now actually show. Please test that one on your machine; I'm not sure if the fix is version-dependent.

Most of these design changes come courtesy of having used the roll20 sheet. Damn they did some nice work on that thing...

### CODE REVIEW

**Comment by dunderjester** [comment]
The part where the dice do not show is version dependent, it's a breaking change Foundry did in 0.7.x. ( `.roll` became `.result`) so this fix would make the dice disappear for 0.7.x.
I also fixed it in PR #62 😅

**Comment by megastruktur** [comment]
@OctarineSourcerer Hey bro, I made lots of changes for Localization before realized you have some stuff to push.
Can you please take my `development` branch and implement the leftover changes from your pull request and create a new one?

I'd like to do this myself but seems like some changes were already implemented and several code parts are slightly refactored. And I don't want to steal parts of your code and make a commit because then you won't be shown as a contributor.

**Comment by OctarineSourcerer** [comment]
> The part where the dice do not show is version dependent, it's a breaking change Foundry did in 0.7.x. ( `.roll` became `.result`) so this fix would make the dice disappear for 0.7.x.
> I also fixed it in PR #62 sweat_smile

Oh awesome! I'll exclude those changes from my PR then; you've handled this better than I have

**Comment by OctarineSourcerer** [comment]
> @OctarineSourcerer Hey bro, I made lots of changes for Localization before realized you have some stuff to push.
> Can you please take my `development` branch and implement the leftover changes from your pull request and create a new one?
> 
> I'd like to do this myself but seems like some changes were already implemented and several code parts are slightly refactored. And I don't want to steal parts of your code and make a commit because then you won't be shown as a contributor.

Yeah, of course! Much appreciated on the authorship front :)

**Pull request closed without merging**
