### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by bighi**
Complete Portuguese translation using the terms of the official translation that is about to be released in Brazil.

### CODE REVIEW

**Comment by brunocalado** [comment]
oi

**Comment by brunocalado** [comment]
estou fazendo a tradução tambem

vamos trabalhoar juntos?
image

me chama no servidor discord br
Discord Brasil do Foundry VTT https://discord.gg/XNC86FBnQ2

**Comment by brunocalado** [comment]
já está até funcionando a tradução: https://github.com/brunocalado/bid-pt-br

**Comment by brunocalado** [comment]
Please, use this one:
[pt-br.txt](https://github.com/megastruktur/foundryvtt-blades-in-the-dark/files/7071712/pt-br.txt)

**Review by megastruktur — APPROVED** [review]

**Pull request merged**
